#ifndef _PROXY_HPP_INCLUDED_SDOIFJ438OUAFSLSF988923PFUISLFKJEOIJFLKJDOIJFALIJEIJ
#define _PROXY_HPP_INCLUDED_SDOIFJ438OUAFSLSF988923PFUISLFKJEOIJFLKJDOIJFALIJEIJ

namespace vg 
{

template<typename T>
struct proxy : T
{};


}//namespace vg

#endif//_PROXY_HPP_INCLUDED_SDOIFJ438OUAFSLSF988923PFUISLFKJEOIJFLKJDOIJFALIJEIJ

